apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: gama
  name: gama
  namespace: omaml
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gama
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: gama
    spec:
      containers:
      - env:
        - name: GRPC_SERVER_PORT
          value: "50065"
        - name: EXPLAINER_DASHBOARD_PORT_START
          value: "4000"
        - name: EXPLAINER_DASHBOARD_PORT_END
          value: "4010"
        image: alexhda/omaml-gama
        imagePullPolicy: ""
        name: gama
        resources:
          limits:
            cpu: "6"
            memory: "12097152e3"
        volumeMounts:
        - name: datasets
          mountPath: /app/app-data/datasets
        - name: output-gama
          mountPath: /app/app-data/training
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: datasets
        persistentVolumeClaim:
          claimName: datasets-claim
      - name: output-gama
        persistentVolumeClaim:
          claimName: output-gama-claim
