apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mljar
  name: mljar
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mljar
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mljar
    spec:
      containers:
      - env:
        - name: GRPC_SERVER_PORT
          value: "50053"
        image: alexhda/omaml-mljar
        imagePullPolicy: ""
        name: mljar
        resources:
          limits:
            cpu: "1"
            memory: "1097152e3"
        volumeMounts:
        - name: datasets
          mountPath: /app/app-data/datasets
        - name: output-mljar
          mountPath: /app/app-data/training
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: datasets
        persistentVolumeClaim:
          claimName: datasets-claim
      - name: output-mljar
        persistentVolumeClaim:
          claimName: output-mljar-claim
