apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: training-claim
  namespace: omaml
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datasets-claim
  namespace: omaml
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: output-autokeras-claim
  namespace: omaml
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  storageClassName: longhorn-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: output-mljar-claim
  namespace: omaml
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  storageClassName: longhorn-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: output-autogluon-claim
  namespace: omaml
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  storageClassName: longhorn-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: output-flaml-claim
  namespace: omaml
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  storageClassName: longhorn-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: output-pycaret-claim
  namespace: omaml
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  storageClassName: longhorn-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-claim
  namespace: omaml
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbdata-claim
  namespace: omaml
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redisdata-claim
  namespace: omaml
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: output-evalml-claim
  namespace: omaml
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  storageClassName: longhorn-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: output-tpot-claim
  namespace: omaml
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  storageClassName: longhorn-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: output-gama-claim
  namespace: omaml
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  storageClassName: longhorn-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: output-lama-claim
  namespace: omaml
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  storageClassName: longhorn-csi

